services: 
  nexus: 
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - '8081:8081'
      - '8085:8085'
      - '5000:5000'
    volumes:
      - './nexus-data:/nexus-data'
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1200m -Xmx1200m
    restart: always
